### ISSUE TITLE
Connect to mint fails because of trailing slash

### ISSUE THREAD

**Issue by Dayvvo** [cashubtc/cashu-ts#124]
When the mint URL supplied to the CashuMint class contains a trailing URL. the connect request would fail as shown here:
<img width="1680" alt="image" src="https://github.com/cashubtc/cashu-ts/assets/45407706/4062cfe9-2730-4d74-b27d-5d5496da46f5">. This could cause some confusion should for a regular user without technical knowhow

Solution: the CashuMint Class should handle trailing URLS by removing the trailing slash in the class if it exists

**Comment by Dayvvo** [comment]
@callebtc please let me know your thoughts towards this. Looking forward to your response!

**Comment by callebtc** [comment]
Agreed! Please feel free to open an PR!

**Comment by Dayvvo** [comment]
Alright thanks! on it
