### ISSUE TITLE
A set of amount `preference` fixes

### ISSUE THREAD

**Issue by callebtc** [cashubtc/cashu-ts#129]
Some issues I think are worth fixing:

- Allow setting the preference for all outputs of a swap (`createSplitPayload`), not only for `proofsToSend` (but also `proofsToKeep`)
- `splitAmount` seems to "fill up the rest" with 2^n even if `amountPreference` is set. Is this intended?
- Do not check if all amounts are `2^n`, since this is not generally the case. Replace this check by checking if every amount has a key.
- Consider replacing the `AmountPrefernce` object `{ amount: int, count: int }` with a simple `number[]` that holds the requested amounts (feels cleaner to me).

**Comment by lollerfirst** [comment]
My new PR addresses first 3 points. I take it that point 4 is to be discussed.

**Comment by Egge21M** [comment]
@callebtc this is done, right?

**Comment by gandlafbtc** [comment]
will be closed with #159
