### ISSUE TITLE
V1 naming

### ISSUE THREAD

**Issue by Egge21M** [cashubtc/cashu-ts#143]
When helping someone add cashu-ts to their project at the ecash hackathon I realised that some of the method names in the public facing API are a bit ambiguous. Therefore I suggest renaming a few of the CashuWallet methods before releasing v1.0

```ts
mintQuote -> createMintQuote
getMintQuote -> checkMintQuote
```
Reasoning: The HTTP words are often used differently in a programs context. In this case "Mint" should be a noun and not a verb. Changing to `check` makes it clear that we are checking on an already existing quote.

Option: We could also make the API identical with the protocol specifications (e.g. `postMintQuote` and `getMintQuote`, however this would not really increase readability IMHO).

```ts
meltQuote -> createMeltQuote
getMeltQuote -> checkMeltQuote
```
Reasoning: The same as above

```ts
checkProofsSpent -> getSpentProofs 
```
Reasoning: `checkProofsSpent` tells little about the return value of this function. As it takes in a list of Proofs and returns only the spent one `getSpentProofs` makes the functions behaviour clearer.

---

I will go through the Repo once more to see if I missed anything. If everyone is aligned I am happy to open a PR and fix downstream dependents (if there are any).

**Comment by Egge21M** [comment]
Thinking more about this, it might even make more sense to mimic the specifications, resulting in `postMintQuote` and `getMintQuote`. What do you think @gandlafbtc @callebtc ?

**Comment by callebtc** [comment]
> Thinking more about this, it might even make more sense to mimic the specifications, resulting in `postMintQuote` and `getMintQuote`. What do you think @gandlafbtc @callebtc ?

I think I prefer the naming in the original post but I have no strong favorite.
