### ISSUE TITLE
Lack of Formatting Guidelines

### ISSUE THREAD

**Issue by BilligsterUser** [cashubtc/cashu-ts#15]
Our repository lacks clear formatting guidelines, which can lead to inconsistent formatting and styling across the project. This can make it difficult to read and understand the code, and can hinder collaboration between contributors who may have different formatting preferences. To address this issue, we need to implement formatting guidelines that ensure consistency across all files in the repository

We can address this issue by adopting a code formatter like Prettier that can automatically enforce consistent formatting across all files in the repository.

**Comment by gandlafbtc** [comment]
Agreed, very much needed
