### ISSUE TITLE
[Feature request] Support for DLEQ proofs

### ISSUE THREAD

**Issue by callebtc** [cashubtc/cashu-ts#156]
[DLEQ proof spec](https://github.com/cashubtc/nuts/blob/main/12.md). We should support: 
1) verify DLEQ proofs whenever blind signatures are received from a mint that include proofs
2) option to send DLEQ proofs to another user
3) ability to verify DLEQ proofs that we received from another user

**Comment by lollerfirst** [comment]
@callebtc I figured that before we do this we need to implement the necessary tools in the cashu-crypto-ts module.
See my PR: https://github.com/cashubtc/cashu-crypto-ts/pull/2
