### ISSUE TITLE
Discuss: deprecate `payLnInvoice` and `payLnInvoiceWithToken` from lib

### ISSUE THREAD

**Issue by callebtc** [cashubtc/cashu-ts#157]
These helper methods are not needed, the API is now simple enough to leave it up to the implementor to figure out how to do it.

Thoughts?

**Comment by gudnuf** [comment]
agreed, I was previously using these methods but decided I preferred handling paying an invoice in my own way so I no longer use either function in Boardwalk

**Comment by Egge21M** [comment]
Yes I agree. Please mark as deprecated and we will remove them with the next major release.
