### ISSUE TITLE
Wallet: mintTokens does not return a full token

### ISSUE THREAD

**Issue by Egge21M** [cashubtc/cashu-ts#185]
`wallet.mintTokens()` does not return a `Token`, but instead `{ proofs: Array<Proof> }`. I think the method naming is a bit confusing and should probably be changed. 

We could also introduce a new method that takes some optional parameters and actually returns a full `Token`.

**Comment by callebtc** [comment]
It should not return a token, but proofs that can be stored in the db. Naming was changed to `mintProofs` in the PR you linked.

Tokens should not be returned anywhere except for the serializer (which already works). What's missing?

**Comment by Egge21M** [comment]
`Token` refers to the token object here, not the serialised version. However this issue is addressed with the linked PR and can be closed once merged
