### ISSUE TITLE
Default to TokenV4

### ISSUE THREAD

**Issue by callebtc** [cashubtc/cashu-ts#198]
Move `getEncodedToken` to `getEncodedTokenV3` and `getEncodedTokenV4` to `getEncodedToken`.

**Comment by mubarak23** [comment]
@callebtc can you provide a bit more context to this issue, i will love to jump and work on it

**Comment by Egge21M** [comment]
This is already happening and will be in the next release. I linked the PR

**Comment by mubarak23** [comment]
> This is already happening and will be in the next release. I linked the PR

looking for "Good First Issue" to work on

**Comment by Egge21M** [comment]
> looking for "Good First Issue" to work on

Awesome, much appreciated! I'll make sure to tag some later today!
