### ISSUE TITLE
Return unused proofs as change in send function

### ISSUE THREAD

**Issue by gandlafbtc** [cashubtc/cashu-ts#22]
https://github.com/cashubtc/cashu-ts/blob/main/src/CashuWallet.ts?plain=1#L96

It might be better to return proofs that enter the method but are not sent to the mint with the change

**Comment by BilligsterUser** [comment]
do you mean https://github.com/cashubtc/cashu-ts/blob/main/src/CashuWallet.ts#L103 ?

**Comment by gandlafbtc** [comment]
no, i mean L96, because that's where the proofs get skipped if too many are passed in. They don't get sent to the mint but also not returned as change. i think they should be returned as change

**Comment by BilligsterUser** [comment]
ahh ok
