### ISSUE TITLE
BUG: Check if keys have changed before creating proofs

### ISSUE THREAD

**Issue by gandlafbtc** [cashubtc/cashu-ts#45]
If the mint has changed keys, but the wallet does not recognize it, it might create broken proofs.  

Possible solution: 
* Calculate the current (wallet) mint keyset id from all keys according to [NUT-02](https://github.com/cashubtc/nuts/blob/main/02.md)
* compare with the id inside the received `BlindedSignature`
* If they don't match, we have to load the new keys and perform the unblinding after that

**Comment by BilligsterUser** [comment]
can we close this?

**Comment by gandlafbtc** [comment]
#64 closes this
