### ISSUE TITLE
Switch from noble-secp256k1 to noble-curves

### ISSUE THREAD

**Issue by BilligsterUser** [cashubtc/cashu-ts#47]
https://github.com/paulmillr/noble-secp256k1#upgrading

https://github.com/paulmillr/noble-curves

https://github.com/paulmillr/noble-curves#security

https://github.com/paulmillr/noble-curves#upgrading

example

https://github.com/BilligsterUser/Blind-Signatures/blob/main/src/model/BlindedMessage.ts

**Comment by gandlafbtc** [comment]
what's the benefit of noble-curves? If it's just speed, I'm not sure if we need it.

**Comment by gandlafbtc** [comment]
ok nevermind, i just read the last link, looks like the work will continue on noble-curves 👍

**Comment by BilligsterUser** [comment]
yes

**Comment by BilligsterUser** [comment]
https://github.com/BilligsterUser/cashu-ts/commit/04abeb4f11e2d4d8f4121108183369a5ad023df6
https://github.com/BilligsterUser/cashu-ts/tree/noble-curves
https://github.com/BilligsterUser/cashu-ts/actions/runs/4725203004/jobs/8383312146


hashToCurve tests are failing

maybe you can take a look at it

**Comment by paulmillr** [comment]
node.js 14 is not supported since May, hence `crypto.getRandomValues` error. You should remove it from your CI and replace with node.js 20.

**Comment by BilligsterUser** [comment]
Done thank you
