### ISSUE TITLE
`CashuWallet()` wants `keys` and `mint`, `keys` seems redundant

### ISSUE THREAD

**Issue by callebtc** [cashubtc/cashu-ts#53]
`CashuWallet()` wants `keys` and `mint` as arguments. Isn't`keys` argument not redundant? 

I think it would be nicer to have only one and get the keys, either in the constructor of the `CashuMint` or (maybe better) when they are needed in `CashuWallet` (right after `step3_Alice` afaik).

```typescript
const mint = new CashuMint(MINTURL);
const keys = await mint.getKeys();
const wallet = new CashuWallet(keys, mint);
```

**Comment by BilligsterUser** [comment]
I agree

**Comment by gandlafbtc** [comment]
hmm do we still have the option to set the keys from outside the class? I think that's a must.

**Comment by BilligsterUser** [comment]
For now keys is public. I like to make it private soon but i will add a public setter bc we have to recalc the keysetId If we set new keys

**Comment by gandlafbtc** [comment]
sorry, fat fingers.
