### ISSUE TITLE
Feature request: LN API primitives for cashu-ts

### ISSUE THREAD

**Issue by callebtc** [cashubtc/cashu-ts#67]
I have a feature request for cashu-ts! Lightning API primitives:

```
- /balance - returns the balance
- /createInvoice - creates an invoice and returns bolt11 pr
- /createPayment - pays an invoice and blocks until paid or failed
- /checkInvoice - checks whether an incoming invoice is paid. Lookup by pr or payment_hash and returns True, False, None (if nonexistent)
- /checkPayment - checks whether an outgoing payment is paid. Lookup by pr or payment_hash and returns True, False, None (if nonexistent)
```

I also want to add this to Nutshell. I haven't figured out what the best method would be to implement `checkInvoice` and `checkPayment`.

- `checkInvoice` could be a simple [NUT-04 mint](https://github.com/cashubtc/nuts/blob/main/04.md) (if paid, mints tokens) that returns the result of the mint (attempt)
- `checkPayment` would need a bit more: Either the mint would need an endpoint for `checkPayment` that the lib can just use (might be useful or necessary for other reasons as well?) – OR – the lib could remember which outgoing tokens are reserved for which invoice (in some state it remembers) and then use [NUT-07 token spendable check](https://github.com/cashubtc/nuts/blob/main/07.md) - to figure out whether the payment has gone through or not. I like the latter approach!

If this works, Cashu can be used as almost any LN wallet connector out there. Example of how Alby does it [here](https://github.com/getAlby/lightning-browser-extension/blob/a8813dae2537797f851131583ea9f6ea2ad12798/src/extension/background-script/connectors/connector.interface.ts). Or LNbits [here](https://github.com/lnbits/lnbits/blob/main/lnbits/wallets/void.py).

**Comment by BilligsterUser** [comment]
like 
```typescript
export interface IInvoiceRequest {
	amount: number; // in satoshis
	memo?: string;
	expiry?: number;
}
const walletInvoiceState ={
	Pending : 0,
	Paid : 1,
	Expired : 2,
	Failed : 3,
} as const
export type WalletInvoiceState = keyof typeof walletInvoiceState;
export interface IWalletInvoice {
	pr: string;
	paymentHash: string;
	memo: string;
	amount: number; // in milisatoshis
	fees: number;
	timestamp: number;
	preimage?: string;
	state: WalletInvoiceState;
}
export interface ICheckPaymentArgs {
	paymentHash: string;
}
export interface ICheckPaymentResponse {
	data: {
		paid: boolean;
		preimage?: string;
	};
}
export interface LNWallet {
	getBalance: () => Promise<number>; // in satoshis
	createInvoice: (req: IInvoiceRequest) => Promise<IWalletInvoice>;
	checkPayment: (req: ICheckPaymentArgs) => Promise<ICheckPaymentResponse>;
	checkInvoice: (req: ICheckPaymentArgs) => Promise<ICheckPaymentResponse>;
	payInvoice: (pr: string) => Promise<IWalletInvoice>;
	getInvoices: () => Promise<IWalletInvoice[]>;

}
```
?

**Comment by gandlafbtc** [comment]
let's do this in a separate lib, since getBalance() requires some sort of state

**Comment by callebtc** [comment]
> let's do this in a separate lib, since getBalance() requires some sort of state

What if `getBalance()` had an argument ingesting proofs that the caller must prodive? It was supposed to be a very short wrapper for counting amounts anyway.
