### ISSUE TITLE
Mint specific proof amounts 

### ISSUE THREAD

**Issue by gandlafbtc** [cashubtc/cashu-ts#75]
The lib should support minting specific proof amounts:

can get inspired by nutshells implementation 

![IMG_20230606_002712_631](https://github.com/cashubtc/cashu-ts/assets/123852829/a59efaa4-6c82-47b7-a5bf-b5efc5e32283)

**Comment by callebtc** [comment]
Update: We have everything in a single `mint` function now with a lot less code:
![image](https://github.com/cashubtc/cashu-ts/assets/93376500/7699340e-4277-4535-8057-c42cee65cdba)
