### ISSUE TITLE
Add utility function to decode LN-invoice 

### ISSUE THREAD

**Issue by gandlafbtc** [cashubtc/cashu-ts#94]
especially amount would be nice. Now it has to be done manually outside of the lib:

```javascript
const amount = decode(invoice).sections[2].value / 1000;
```

**Comment by Egge21M** [comment]
I have written this exact utility a million times and would be happy to add it here. 

But should this really be a utility function, or should the wallet API change in a future major update to return an invoice object that has pr, amount, memo etc?
